### ISSUE TITLE
ch2: Vagrant setup

### ISSUE THREAD

**Issue by seajosh** [rjurney/Agile_Data_Code_2#12]
The reader might need to change this before running ```vagrant up``` depending on their system. I had problems provisioning vagrant until I changed the memory limit to 4GB / 4096; 

```
  config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "9216"
  end
```

**Comment by rjurney** [comment]
The problem is that with less than 9GB of RAM, all of the examples won't run. The model training for instance, and some of the nested records we prepare for MongoDB, they take 9GB. This requires that I close nearly all programs on my newish Macbook Pro with 16GB of RAM. It sucks. I don't know what to do to fix it, other than recommend the EC2 setup.

**Comment by seajosh** [comment]
That's cool - the copy needs to note the minimum system requirements (to the best of your knowledge - no need to be too specific here) for running vagrant locally and a brief explanation of why.

**Comment by rjurney** [comment]
I made the bit about 9GB bold in the book and README bolder and longer/bigger.
